/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package WBTM

class App {

    App() {
        println(33)
    }

    static void main(String[] args) {
        new App()
    }
}
